language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install numpy
- pip install codecov
- pip install .
script:
- coverage run -m unittest discover test/ -p test_*.py
deploy:
  provider: pypi
  user: "$pypi_username"
  password: "$pypi_password"
  on:
    branch: release
after_success:
- codecov
env:
  global:
  - secure: ugm3F6Xc7Bwed+JKfO1dJCD2jVOgVLjj7HssZFibkuDiavCfT0BkipVedeARKzJGRvhCQlqjBg11YsBpqBrZN93t0BaX2igHEY6tnAgT8uLVwPv6HcIG4uEhFGkfG6rqX3aUQXraTSP7b72C1buI3+XwHXc0JLU2OPM2YASoJmns83GnV5m5BlENvV2tuZc3JgZklYHqPOkilBCamw62L03z6yYSnRvRpDmipo6dIcVKtQz5dHzE4DwIUl8yKEdorXX8dc30lfaGArv7FLTKTJG2RnUI+s/FsJFGwB50wnfsiS8XUUDN9os452f9cTTF8C1NbBctpeOZ60UrL2413lb+Nbes9XgyB+oUZTtKXY9WURZOD/qfdZWjlIADtwnziwcju8276zES695sxHjWRjyUH9RkStwN7P/yjWEuYq5Nmm75RoEBmzdbSGEhY4lDp/YSU6ZHusmMB434i0R32A85y8vmold91h5EQHCqpCnU+qIq5vMl1FNPWCRQ5N1wzmCfaCwyaPp8HG3RruzCjDyVOVzTIUz2z9+I7ikXdCZYGzjR6JeivoyIU7ZLQ8x7qzy4hkLaaqIIRNDHicUCEUJUCMSJ+RHO06MnMMZGKsY5KoeHrwaFyovDUBznLOJgLpC5Ell/DMCpP9ouSYrTydmbFDRnFpxP74Zm5kESD4k=
  - secure: jMMI47te8CG8txKmXrZ5rBYl5sz8Zp1pVPymegsiM1VTr96w1TK94aZkXM/SsoNewiYCCtBmUZdYP+nPAU6+H4B5lAz6jazmXPPReWN0Xg1hXGhfI2X2zfpSzSU9dJtGVmsBCjniwKL3Hdof9hkHbKnOUAf7EmhJDmepIVl/vKDWvq+2tA3MtF/7pCyxMDiFpx2peE6d0QfzVNEWkvsr7KNJ6y8zWGrHupPlc0iFviry3jHrsRdQCbx29JDObAomNNOxp3WgKj7VMCJbOJlUiSYN308yfZtvlpiAQyr/Ng/ZPv9NrrsoBICFjgY4vdH03rZ8pgdZ7y5B8cROsl36wYnlZI150QKe3Yrg4GkpW/FI2HtedISwAo6zzCytNLl7WvUqmJmaXAriuq9Gu+agIZ6uTwjJSRYUuCtwKbjYXtp0ZDUAYDnn1LzkO/8tBC07784bdhv/6YM3+gVBoGhxYl7r2uf6AO15qGKYQ/KuxSI2hEd0aIdCtUTruuH16Ew3f6amDjXybMf4ldjV+Dx2Ua2V2hq+Gyp7jCR0aTCRplxwLc5iGCJg4xiWuAegJgrDoh+PD3V5OJVAZkIwv43WuaK3lOtLnH2Lp/o7EHnttNprt11HQSz9SjTjafVEbYXClkakHKjQ77C7WtPGSnqzgt8wK/sw+04kZhMhdweJpj0=
